swagger: "2.0"
info:
  title: Augeu
  description: Augeu api
  version: 0.0.1
schemes:
  - https
  - http

basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json


paths:
  /version:
    get:
      security: [ ]
      responses:
        200:
          description: "返回 BrightPath Api 版本号"
          schema:
            $ref: "#/definitions/Version"

  /getClientId:
    post:
      security: [ ]
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/GetClientIdRequest"
      responses:
        200:
          description: "返回 BrightPath Api 版本号"
          schema:
            $ref: "#/definitions/GetClientIdResponse"
        401:
          description: "没有权限"
          schema:
            $ref: "#/definitions/UnauthorizedError"
        500:
          description: "内部错误"
          schema:
            $ref: "#/definitions/ActionFailure"

  /login:
    post:
      security: [ ]
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        200:
          description: "登录成功，返回 JWT 令牌"
          schema:
            $ref: "#/definitions/LoginResponse"
        401:
          description: "用户名或密码错误"
          schema:
            $ref: "#/definitions/UnauthorizedError"
        500:
          description: "内部错误"
          schema:
            $ref: "#/definitions/ActionFailure"
  /register:
    post:
      security: [ ]
      parameters:
        - in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/RegisterRequest"
      responses:
        200:
          description: "注册成功"
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: "输入参数错误"
          schema:
            $ref: "#/definitions/BadRequestError"
        500:
          description: "内部错误"
          schema:
            $ref: "#/definitions/ActionFailure"

definitions:
  Version:
    type: object
    properties:
      version:
        type: string
        description: "版本号"
        default: 0.0.1

  PageMeta:
    type: object
    properties:
      total:
        type: integer
      page:
        type: integer
        default: 1
      size:
        type: integer
        default: 10

  UnauthorizedError:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
        description: "没有权限"
      code:
        type: integer
        description: "403"

  ActionFailure:
    type: object
    required:
      - success
      - from
      - reason
    properties:
      success:
        type: boolean
        default: false
      from:
        type: string
        default: "unknown"
      reason:
        type: string
        default: "unexpected stack overflow"

  GetClientIdResponse:
    type: object
    required:
      - success
      - clientId
    properties:
      success:
        type: boolean
        default: true
      clientId:
        type: string
        default: "unknown"
      jwt:
        type: string

  GetClientIdRequest:
    type: object
    required:
      - uuid
      - secret
      - ip
      - system_info
    properties:
      uuid:
        type: string
        description: "唯一标识符"
      secret:
        type: string
        description: "密钥"
      ip:
        type: array
        items:
          type: string
        description: "IP 地址列表"
      system_info:
        $ref: "#/definitions/SystemInfo"
        description: "系统信息"

  SystemInfo:
    type: object
    required:
      - os_name
      - os_version
      - os_arch
      - patchs
    properties:
      os_name:
        type: string
        description: "操作系统名称"
      os_version:
        type: string
        description: "操作系统版本"
      os_arch:
        type: string
        description: "操作系统架构"
      patchs:
        type: array
        items:
          $ref: "#/definitions/Patch"
        description: "补丁列表"

  Patch:
    type: object
    required:
      - Description
      - HotFixID
      - InstalledBy
      - InstalledOn
    properties:
      Description:
        type: string
        description: "补丁描述"
      HotFixID:
        type: string
        description: "热修复 ID"
      InstalledBy:
        type: string
        description: "安装者"
      InstalledOn:
        type: string
        description: "安装时间"

  LoginRequest:
    type: object
    required:
      - secrete
      - name
      - password
    properties:
      secrete:
        type: string
        description: "server 提供的secrete"
      name:
        type: string
        description: "用户名"
      password:
        type: string
        description: "密码"

  LoginResponse:
    type: object
    required:
      - success
      - jwt
    properties:
      success:
        type: boolean
        default: true
        description: "是否成功"
      jwt:
        type: string
        description: "JWT 令牌"
        default: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        # 登陆失败搞个 假的 jwt 搞心态

  RegisterRequest:
    type: object
    required:
      - userName
      - passWord
      - secrete
    properties:
      userName:
        type: string
        description: "用户名"
      passWord:
        type: string
        description: "密码"
      secrete:
        type: string
        description: "server 提供的token"


  RegisterResponse:
    type: object
    required:
      - success
      - message
    properties:
      success:
        type: boolean
        default: true
      message:
        type: string
        default: "注册成功"

  BadRequestError:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
        description: "输入参数错误"
      code:
        type: integer
        description: "400"

