swagger: "2.0"
info:
  title: Augeu
  description: Augeu api
  version: 0.0.1
schemes:
  - https
  - http

basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json


paths:
  /version:
    get:
      security: [ ]
      responses:
        200:
          description: "返回 BrightPath Api 版本号"
          schema:
            $ref: "#/definitions/Version"

  /getClientId:
    post:
      security: [ ]
      parameters:
        - in: body
          name: data
          required: true
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: "客户端名称"
              secret:
                type: string
                description: "客户端密钥"
      responses:
        200:
          description: "返回 BrightPath Api 版本号"
          schema:
            $ref: "#/definitions/GetClientIdResponse"
        401:
          description: "没有权限"
          schema:
            $ref: "#/definitions/UnauthorizedError"
        500:
          description: "内部错误"
          schema:
            $ref: "#/definitions/ActionFailure"

definitions:
  Version:
    type: object
    properties:
      version:
        type: string
        description: "版本号"
        default: 0.0.1

  PageMeta:
    type: object
    properties:
      total:
        type: integer
      page:
        type: integer
        default: 1
      size:
        type: integer
        default: 10

  UnauthorizedError:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
        description: "没有权限"
      code:
        type: integer
        description: "403"

  ActionFailure:
    type: object
    required:
      - success
      - from
      - reason
    properties:
      success:
        type: boolean
        default: false
      from:
        type: string
        default: "unknown"
      reason:
        type: string
        default: "unexpected stack overflow"

  GetClientIdResponse:
    type: object
    required:
      - success
      - clientId
    properties:
      success:
        type: boolean
        default: true
      clientId:
        type: string
        default: "unknown"
      jwt:
        type: string