websocket:
  remoteAddr: "ws://127.0.0.1:8080"


databaseConf:
  Host: "139.159.140.145"
  Port: 5432
  Username: "postgres"
  Password: "1qazXSW@3edcVFR$!@#$,./"
  Dbname: "dewu"
  TimeOut: 100000000
  DbFilePath: ""
  DbType: "postgres" # mysql, postgres, sqlite3