// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGetRulesHandlerFunc turns a function with the right signature into a get get rules handler
type GetGetRulesHandlerFunc func(GetGetRulesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGetRulesHandlerFunc) Handle(params GetGetRulesParams) middleware.Responder {
	return fn(params)
}

// GetGetRulesHandler interface for that can handle valid get get rules params
type GetGetRulesHandler interface {
	Handle(GetGetRulesParams) middleware.Responder
}

// NewGetGetRules creates a new http.Handler for the get get rules operation
func NewGetGetRules(ctx *middleware.Context, handler GetGetRulesHandler) *GetGetRules {
	return &GetGetRules{Context: ctx, Handler: handler}
}

/*
	GetGetRules swagger:route GET /get/rules getGetRules

查询规则列表
*/
type GetGetRules struct {
	Context *middleware.Context
	Handler GetGetRulesHandler
}

func (o *GetGetRules) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGetRulesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
