// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// GetGetRulesOKCode is the HTTP code returned for type GetGetRulesOK
const GetGetRulesOKCode int = 200

/*
GetGetRulesOK 成功返回规则列表

swagger:response getGetRulesOK
*/
type GetGetRulesOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetRulesResponse `json:"body,omitempty"`
}

// NewGetGetRulesOK creates GetGetRulesOK with default headers values
func NewGetGetRulesOK() *GetGetRulesOK {

	return &GetGetRulesOK{}
}

// WithPayload adds the payload to the get get rules o k response
func (o *GetGetRulesOK) WithPayload(payload *models.GetRulesResponse) *GetGetRulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get rules o k response
func (o *GetGetRulesOK) SetPayload(payload *models.GetRulesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetRulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetRulesBadRequestCode is the HTTP code returned for type GetGetRulesBadRequest
const GetGetRulesBadRequestCode int = 400

/*
GetGetRulesBadRequest 输入参数错误

swagger:response getGetRulesBadRequest
*/
type GetGetRulesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewGetGetRulesBadRequest creates GetGetRulesBadRequest with default headers values
func NewGetGetRulesBadRequest() *GetGetRulesBadRequest {

	return &GetGetRulesBadRequest{}
}

// WithPayload adds the payload to the get get rules bad request response
func (o *GetGetRulesBadRequest) WithPayload(payload *models.BadRequestError) *GetGetRulesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get rules bad request response
func (o *GetGetRulesBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetRulesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetRulesForbiddenCode is the HTTP code returned for type GetGetRulesForbidden
const GetGetRulesForbiddenCode int = 403

/*
GetGetRulesForbidden 没有权限

swagger:response getGetRulesForbidden
*/
type GetGetRulesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.UnauthorizedError `json:"body,omitempty"`
}

// NewGetGetRulesForbidden creates GetGetRulesForbidden with default headers values
func NewGetGetRulesForbidden() *GetGetRulesForbidden {

	return &GetGetRulesForbidden{}
}

// WithPayload adds the payload to the get get rules forbidden response
func (o *GetGetRulesForbidden) WithPayload(payload *models.UnauthorizedError) *GetGetRulesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get rules forbidden response
func (o *GetGetRulesForbidden) SetPayload(payload *models.UnauthorizedError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetRulesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetRulesInternalServerErrorCode is the HTTP code returned for type GetGetRulesInternalServerError
const GetGetRulesInternalServerErrorCode int = 500

/*
GetGetRulesInternalServerError 内部错误

swagger:response getGetRulesInternalServerError
*/
type GetGetRulesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ActionFailure `json:"body,omitempty"`
}

// NewGetGetRulesInternalServerError creates GetGetRulesInternalServerError with default headers values
func NewGetGetRulesInternalServerError() *GetGetRulesInternalServerError {

	return &GetGetRulesInternalServerError{}
}

// WithPayload adds the payload to the get get rules internal server error response
func (o *GetGetRulesInternalServerError) WithPayload(payload *models.ActionFailure) *GetGetRulesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get rules internal server error response
func (o *GetGetRulesInternalServerError) SetPayload(payload *models.ActionFailure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetRulesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
