// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetSecurityEventOKCode is the HTTP code returned for type PostGetSecurityEventOK
const PostGetSecurityEventOKCode int = 200

/*
PostGetSecurityEventOK 成功返回事件数组

swagger:response postGetSecurityEventOK
*/
type PostGetSecurityEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.SecurityEvent `json:"body,omitempty"`
}

// NewPostGetSecurityEventOK creates PostGetSecurityEventOK with default headers values
func NewPostGetSecurityEventOK() *PostGetSecurityEventOK {

	return &PostGetSecurityEventOK{}
}

// WithPayload adds the payload to the post get security event o k response
func (o *PostGetSecurityEventOK) WithPayload(payload []*models.SecurityEvent) *PostGetSecurityEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get security event o k response
func (o *PostGetSecurityEventOK) SetPayload(payload []*models.SecurityEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetSecurityEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.SecurityEvent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
