// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostUpdataRdpEventOKCode is the HTTP code returned for type PostUpdataRdpEventOK
const PostUpdataRdpEventOKCode int = 200

/*
PostUpdataRdpEventOK 上传成功

swagger:response postUpdataRdpEventOK
*/
type PostUpdataRdpEventOK struct {

	/*
	  In: Body
	*/
	Payload *models.RDPEventUpload `json:"body,omitempty"`
}

// NewPostUpdataRdpEventOK creates PostUpdataRdpEventOK with default headers values
func NewPostUpdataRdpEventOK() *PostUpdataRdpEventOK {

	return &PostUpdataRdpEventOK{}
}

// WithPayload adds the payload to the post updata rdp event o k response
func (o *PostUpdataRdpEventOK) WithPayload(payload *models.RDPEventUpload) *PostUpdataRdpEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata rdp event o k response
func (o *PostUpdataRdpEventOK) SetPayload(payload *models.RDPEventUpload) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataRdpEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
