// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetFileReportOKCode is the HTTP code returned for type PostGetFileReportOK
const PostGetFileReportOKCode int = 200

/*
PostGetFileReportOK 上传成功

swagger:response postGetFileReportOK
*/
type PostGetFileReportOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetFileReportResponse `json:"body,omitempty"`
}

// NewPostGetFileReportOK creates PostGetFileReportOK with default headers values
func NewPostGetFileReportOK() *PostGetFileReportOK {

	return &PostGetFileReportOK{}
}

// WithPayload adds the payload to the post get file report o k response
func (o *PostGetFileReportOK) WithPayload(payload *models.GetFileReportResponse) *PostGetFileReportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get file report o k response
func (o *PostGetFileReportOK) SetPayload(payload *models.GetFileReportResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetFileReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostGetFileReportBadRequestCode is the HTTP code returned for type PostGetFileReportBadRequest
const PostGetFileReportBadRequestCode int = 400

/*
PostGetFileReportBadRequest 输入参数错误

swagger:response postGetFileReportBadRequest
*/
type PostGetFileReportBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewPostGetFileReportBadRequest creates PostGetFileReportBadRequest with default headers values
func NewPostGetFileReportBadRequest() *PostGetFileReportBadRequest {

	return &PostGetFileReportBadRequest{}
}

// WithPayload adds the payload to the post get file report bad request response
func (o *PostGetFileReportBadRequest) WithPayload(payload *models.BadRequestError) *PostGetFileReportBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get file report bad request response
func (o *PostGetFileReportBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetFileReportBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostGetFileReportForbiddenCode is the HTTP code returned for type PostGetFileReportForbidden
const PostGetFileReportForbiddenCode int = 403

/*
PostGetFileReportForbidden 没有权限

swagger:response postGetFileReportForbidden
*/
type PostGetFileReportForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.UnauthorizedError `json:"body,omitempty"`
}

// NewPostGetFileReportForbidden creates PostGetFileReportForbidden with default headers values
func NewPostGetFileReportForbidden() *PostGetFileReportForbidden {

	return &PostGetFileReportForbidden{}
}

// WithPayload adds the payload to the post get file report forbidden response
func (o *PostGetFileReportForbidden) WithPayload(payload *models.UnauthorizedError) *PostGetFileReportForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get file report forbidden response
func (o *PostGetFileReportForbidden) SetPayload(payload *models.UnauthorizedError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetFileReportForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostGetFileReportInternalServerErrorCode is the HTTP code returned for type PostGetFileReportInternalServerError
const PostGetFileReportInternalServerErrorCode int = 500

/*
PostGetFileReportInternalServerError 内部错误

swagger:response postGetFileReportInternalServerError
*/
type PostGetFileReportInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ActionFailure `json:"body,omitempty"`
}

// NewPostGetFileReportInternalServerError creates PostGetFileReportInternalServerError with default headers values
func NewPostGetFileReportInternalServerError() *PostGetFileReportInternalServerError {

	return &PostGetFileReportInternalServerError{}
}

// WithPayload adds the payload to the post get file report internal server error response
func (o *PostGetFileReportInternalServerError) WithPayload(payload *models.ActionFailure) *PostGetFileReportInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get file report internal server error response
func (o *PostGetFileReportInternalServerError) SetPayload(payload *models.ActionFailure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetFileReportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
