// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdataApplicationEventOKCode is the HTTP code returned for type PostUpdataApplicationEventOK
const PostUpdataApplicationEventOKCode int = 200

/*
PostUpdataApplicationEventOK 上传成功

swagger:response postUpdataApplicationEventOK
*/
type PostUpdataApplicationEventOK struct {
}

// NewPostUpdataApplicationEventOK creates PostUpdataApplicationEventOK with default headers values
func NewPostUpdataApplicationEventOK() *PostUpdataApplicationEventOK {

	return &PostUpdataApplicationEventOK{}
}

// WriteResponse to the client
func (o *PostUpdataApplicationEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
