// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdataServiceEventOKCode is the HTTP code returned for type PostUpdataServiceEventOK
const PostUpdataServiceEventOKCode int = 200

/*
PostUpdataServiceEventOK 上传成功

swagger:response postUpdataServiceEventOK
*/
type PostUpdataServiceEventOK struct {
}

// NewPostUpdataServiceEventOK creates PostUpdataServiceEventOK with default headers values
func NewPostUpdataServiceEventOK() *PostUpdataServiceEventOK {

	return &PostUpdataServiceEventOK{}
}

// WriteResponse to the client
func (o *PostUpdataServiceEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
