// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetProcessEventOKCode is the HTTP code returned for type PostGetProcessEventOK
const PostGetProcessEventOKCode int = 200

/*
PostGetProcessEventOK 成功返回事件数组

swagger:response postGetProcessEventOK
*/
type PostGetProcessEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.EventCreateProcess `json:"body,omitempty"`
}

// NewPostGetProcessEventOK creates PostGetProcessEventOK with default headers values
func NewPostGetProcessEventOK() *PostGetProcessEventOK {

	return &PostGetProcessEventOK{}
}

// WithPayload adds the payload to the post get process event o k response
func (o *PostGetProcessEventOK) WithPayload(payload []*models.EventCreateProcess) *PostGetProcessEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get process event o k response
func (o *PostGetProcessEventOK) SetPayload(payload []*models.EventCreateProcess) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetProcessEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.EventCreateProcess, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
