// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetPowershellEventOKCode is the HTTP code returned for type PostGetPowershellEventOK
const PostGetPowershellEventOKCode int = 200

/*
PostGetPowershellEventOK 成功返回事件数组

swagger:response postGetPowershellEventOK
*/
type PostGetPowershellEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.EventPowerShell `json:"body,omitempty"`
}

// NewPostGetPowershellEventOK creates PostGetPowershellEventOK with default headers values
func NewPostGetPowershellEventOK() *PostGetPowershellEventOK {

	return &PostGetPowershellEventOK{}
}

// WithPayload adds the payload to the post get powershell event o k response
func (o *PostGetPowershellEventOK) WithPayload(payload []*models.EventPowerShell) *PostGetPowershellEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get powershell event o k response
func (o *PostGetPowershellEventOK) SetPayload(payload []*models.EventPowerShell) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetPowershellEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.EventPowerShell, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
