// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdataSecurityEventOKCode is the HTTP code returned for type PostUpdataSecurityEventOK
const PostUpdataSecurityEventOKCode int = 200

/*
PostUpdataSecurityEventOK 上传成功

swagger:response postUpdataSecurityEventOK
*/
type PostUpdataSecurityEventOK struct {
}

// NewPostUpdataSecurityEventOK creates PostUpdataSecurityEventOK with default headers values
func NewPostUpdataSecurityEventOK() *PostUpdataSecurityEventOK {

	return &PostUpdataSecurityEventOK{}
}

// WriteResponse to the client
func (o *PostUpdataSecurityEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
