// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetServiceEventOKCode is the HTTP code returned for type PostGetServiceEventOK
const PostGetServiceEventOKCode int = 200

/*
PostGetServiceEventOK 成功返回服务事件数组

swagger:response postGetServiceEventOK
*/
type PostGetServiceEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ServiceInfo `json:"body,omitempty"`
}

// NewPostGetServiceEventOK creates PostGetServiceEventOK with default headers values
func NewPostGetServiceEventOK() *PostGetServiceEventOK {

	return &PostGetServiceEventOK{}
}

// WithPayload adds the payload to the post get service event o k response
func (o *PostGetServiceEventOK) WithPayload(payload []*models.ServiceInfo) *PostGetServiceEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get service event o k response
func (o *PostGetServiceEventOK) SetPayload(payload []*models.ServiceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetServiceEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ServiceInfo, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
