// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdataProcessEventOKCode is the HTTP code returned for type PostUpdataProcessEventOK
const PostUpdataProcessEventOKCode int = 200

/*
PostUpdataProcessEventOK 上传成功

swagger:response postUpdataProcessEventOK
*/
type PostUpdataProcessEventOK struct {
}

// NewPostUpdataProcessEventOK creates PostUpdataProcessEventOK with default headers values
func NewPostUpdataProcessEventOK() *PostUpdataProcessEventOK {

	return &PostUpdataProcessEventOK{}
}

// WriteResponse to the client
func (o *PostUpdataProcessEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
