// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetFileReportHandlerFunc turns a function with the right signature into a post get file report handler
type PostGetFileReportHandlerFunc func(PostGetFileReportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetFileReportHandlerFunc) Handle(params PostGetFileReportParams) middleware.Responder {
	return fn(params)
}

// PostGetFileReportHandler interface for that can handle valid post get file report params
type PostGetFileReportHandler interface {
	Handle(PostGetFileReportParams) middleware.Responder
}

// NewPostGetFileReport creates a new http.Handler for the post get file report operation
func NewPostGetFileReport(ctx *middleware.Context, handler PostGetFileReportHandler) *PostGetFileReport {
	return &PostGetFileReport{Context: ctx, Handler: handler}
}

/*
	PostGetFileReport swagger:route POST /get/file/report postGetFileReport

获取文件信誉报告
*/
type PostGetFileReport struct {
	Context *middleware.Context
	Handler PostGetFileReportHandler
}

func (o *PostGetFileReport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetFileReportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
