// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdataSystemEventOKCode is the HTTP code returned for type PostUpdataSystemEventOK
const PostUpdataSystemEventOKCode int = 200

/*
PostUpdataSystemEventOK 上传成功

swagger:response postUpdataSystemEventOK
*/
type PostUpdataSystemEventOK struct {
}

// NewPostUpdataSystemEventOK creates PostUpdataSystemEventOK with default headers values
func NewPostUpdataSystemEventOK() *PostUpdataSystemEventOK {

	return &PostUpdataSystemEventOK{}
}

// WriteResponse to the client
func (o *PostUpdataSystemEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
