// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetApplicationEventOKCode is the HTTP code returned for type PostGetApplicationEventOK
const PostGetApplicationEventOKCode int = 200

/*
PostGetApplicationEventOK 成功返回事件数组

swagger:response postGetApplicationEventOK
*/
type PostGetApplicationEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ApplicationEvent `json:"body,omitempty"`
}

// NewPostGetApplicationEventOK creates PostGetApplicationEventOK with default headers values
func NewPostGetApplicationEventOK() *PostGetApplicationEventOK {

	return &PostGetApplicationEventOK{}
}

// WithPayload adds the payload to the post get application event o k response
func (o *PostGetApplicationEventOK) WithPayload(payload []*models.ApplicationEvent) *PostGetApplicationEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get application event o k response
func (o *PostGetApplicationEventOK) SetPayload(payload []*models.ApplicationEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetApplicationEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ApplicationEvent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
