// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetLoginEventOKCode is the HTTP code returned for type PostGetLoginEventOK
const PostGetLoginEventOKCode int = 200

/*
PostGetLoginEventOK 成功返回事件数组

swagger:response postGetLoginEventOK
*/
type PostGetLoginEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.LoginEvent `json:"body,omitempty"`
}

// NewPostGetLoginEventOK creates PostGetLoginEventOK with default headers values
func NewPostGetLoginEventOK() *PostGetLoginEventOK {

	return &PostGetLoginEventOK{}
}

// WithPayload adds the payload to the post get login event o k response
func (o *PostGetLoginEventOK) WithPayload(payload []*models.LoginEvent) *PostGetLoginEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get login event o k response
func (o *PostGetLoginEventOK) SetPayload(payload []*models.LoginEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetLoginEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.LoginEvent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
