// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostGetSystemEventOKCode is the HTTP code returned for type PostGetSystemEventOK
const PostGetSystemEventOKCode int = 200

/*
PostGetSystemEventOK 成功返回事件数组

swagger:response postGetSystemEventOK
*/
type PostGetSystemEventOK struct {

	/*
	  In: Body
	*/
	Payload []*models.SystemEvent `json:"body,omitempty"`
}

// NewPostGetSystemEventOK creates PostGetSystemEventOK with default headers values
func NewPostGetSystemEventOK() *PostGetSystemEventOK {

	return &PostGetSystemEventOK{}
}

// WithPayload adds the payload to the post get system event o k response
func (o *PostGetSystemEventOK) WithPayload(payload []*models.SystemEvent) *PostGetSystemEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get system event o k response
func (o *PostGetSystemEventOK) SetPayload(payload []*models.SystemEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetSystemEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.SystemEvent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
