// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Augeu api",
    "title": "Augeu",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/getClientId": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetClientIdRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "返回 BrightPath Api 版本号",
            "schema": {
              "$ref": "#/definitions/GetClientIdResponse"
            }
          },
          "401": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/version": {
      "get": {
        "security": [],
        "responses": {
          "200": {
            "description": "返回 BrightPath Api 版本号",
            "schema": {
              "$ref": "#/definitions/Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionFailure": {
      "type": "object",
      "required": [
        "success",
        "from",
        "reason"
      ],
      "properties": {
        "from": {
          "type": "string",
          "default": "unknown"
        },
        "reason": {
          "type": "string",
          "default": "unexpected stack overflow"
        },
        "success": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "GetClientIdRequest": {
      "type": "object",
      "required": [
        "uuid",
        "secret",
        "ip",
        "system_info"
      ],
      "properties": {
        "ip": {
          "description": "IP 地址列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "secret": {
          "description": "密钥",
          "type": "string"
        },
        "system_info": {
          "description": "系统信息",
          "$ref": "#/definitions/SystemInfo"
        },
        "uuid": {
          "description": "唯一标识符",
          "type": "string"
        }
      }
    },
    "GetClientIdResponse": {
      "type": "object",
      "required": [
        "success",
        "clientId"
      ],
      "properties": {
        "clientId": {
          "type": "string",
          "default": "unknown"
        },
        "jwt": {
          "type": "string"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "PageMeta": {
      "type": "object",
      "properties": {
        "page": {
          "type": "integer",
          "default": 1
        },
        "size": {
          "type": "integer",
          "default": 10
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "Patch": {
      "type": "object",
      "required": [
        "Description",
        "HotFixID",
        "InstalledBy",
        "InstalledOn"
      ],
      "properties": {
        "Description": {
          "description": "补丁描述",
          "type": "string"
        },
        "HotFixID": {
          "description": "热修复 ID",
          "type": "string"
        },
        "InstalledBy": {
          "description": "安装者",
          "type": "string"
        },
        "InstalledOn": {
          "description": "安装时间",
          "type": "string"
        }
      }
    },
    "SystemInfo": {
      "type": "object",
      "required": [
        "os_name",
        "os_version",
        "os_arch",
        "patchs"
      ],
      "properties": {
        "os_arch": {
          "description": "操作系统架构",
          "type": "string"
        },
        "os_name": {
          "description": "操作系统名称",
          "type": "string"
        },
        "os_version": {
          "description": "操作系统版本",
          "type": "string"
        },
        "patchs": {
          "description": "补丁列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Patch"
          }
        }
      }
    },
    "UnauthorizedError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "403",
          "type": "integer"
        },
        "message": {
          "description": "没有权限",
          "type": "string"
        }
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "version": {
          "description": "版本号",
          "type": "string",
          "default": "0.0.1"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Augeu api",
    "title": "Augeu",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/getClientId": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetClientIdRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "返回 BrightPath Api 版本号",
            "schema": {
              "$ref": "#/definitions/GetClientIdResponse"
            }
          },
          "401": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/version": {
      "get": {
        "security": [],
        "responses": {
          "200": {
            "description": "返回 BrightPath Api 版本号",
            "schema": {
              "$ref": "#/definitions/Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionFailure": {
      "type": "object",
      "required": [
        "success",
        "from",
        "reason"
      ],
      "properties": {
        "from": {
          "type": "string",
          "default": "unknown"
        },
        "reason": {
          "type": "string",
          "default": "unexpected stack overflow"
        },
        "success": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "GetClientIdRequest": {
      "type": "object",
      "required": [
        "uuid",
        "secret",
        "ip",
        "system_info"
      ],
      "properties": {
        "ip": {
          "description": "IP 地址列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "secret": {
          "description": "密钥",
          "type": "string"
        },
        "system_info": {
          "description": "系统信息",
          "$ref": "#/definitions/SystemInfo"
        },
        "uuid": {
          "description": "唯一标识符",
          "type": "string"
        }
      }
    },
    "GetClientIdResponse": {
      "type": "object",
      "required": [
        "success",
        "clientId"
      ],
      "properties": {
        "clientId": {
          "type": "string",
          "default": "unknown"
        },
        "jwt": {
          "type": "string"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "PageMeta": {
      "type": "object",
      "properties": {
        "page": {
          "type": "integer",
          "default": 1
        },
        "size": {
          "type": "integer",
          "default": 10
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "Patch": {
      "type": "object",
      "required": [
        "Description",
        "HotFixID",
        "InstalledBy",
        "InstalledOn"
      ],
      "properties": {
        "Description": {
          "description": "补丁描述",
          "type": "string"
        },
        "HotFixID": {
          "description": "热修复 ID",
          "type": "string"
        },
        "InstalledBy": {
          "description": "安装者",
          "type": "string"
        },
        "InstalledOn": {
          "description": "安装时间",
          "type": "string"
        }
      }
    },
    "SystemInfo": {
      "type": "object",
      "required": [
        "os_name",
        "os_version",
        "os_arch",
        "patchs"
      ],
      "properties": {
        "os_arch": {
          "description": "操作系统架构",
          "type": "string"
        },
        "os_name": {
          "description": "操作系统名称",
          "type": "string"
        },
        "os_version": {
          "description": "操作系统版本",
          "type": "string"
        },
        "patchs": {
          "description": "补丁列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Patch"
          }
        }
      }
    },
    "UnauthorizedError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "403",
          "type": "integer"
        },
        "message": {
          "description": "没有权限",
          "type": "string"
        }
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "version": {
          "description": "版本号",
          "type": "string",
          "default": "0.0.1"
        }
      }
    }
  }
}`))
}
