// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetRulesResponse get rules response
//
// swagger:model GetRulesResponse
type GetRulesResponse struct {

	// 规则内容
	// Required: true
	Data *string `json:"data"`

	// 返回码
	// Required: true
	ResponseCode *int64 `json:"response_code"`
}

// Validate validates this get rules response
func (m *GetRulesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResponseCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetRulesResponse) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

func (m *GetRulesResponse) validateResponseCode(formats strfmt.Registry) error {

	if err := validate.Required("response_code", "body", m.ResponseCode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get rules response based on context it is used
func (m *GetRulesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetRulesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetRulesResponse) UnmarshalBinary(b []byte) error {
	var res GetRulesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
