// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RDPEventUpload r d p event upload
//
// swagger:model RDPEventUpload
type RDPEventUpload struct {

	// description
	Description string `json:"description,omitempty"`

	// event id
	EventID string `json:"event_id,omitempty"`
}

// Validate validates this r d p event upload
func (m *RDPEventUpload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this r d p event upload based on context it is used
func (m *RDPEventUpload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RDPEventUpload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RDPEventUpload) UnmarshalBinary(b []byte) error {
	var res RDPEventUpload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
