// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WeiBuSignatureBase wei bu signature base
//
// swagger:model WeiBuSignatureBase
type WeiBuSignatureBase struct {

	// 描述
	// Required: true
	Description *string `json:"description"`

	// 严重程度
	// Required: true
	Severity *string `json:"severity"`

	// 分类
	// Required: true
	SigClass *string `json:"sigClass"`
}

// Validate validates this wei bu signature base
func (m *WeiBuSignatureBase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSigClass(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WeiBuSignatureBase) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *WeiBuSignatureBase) validateSeverity(formats strfmt.Registry) error {

	if err := validate.Required("severity", "body", m.Severity); err != nil {
		return err
	}

	return nil
}

func (m *WeiBuSignatureBase) validateSigClass(formats strfmt.Registry) error {

	if err := validate.Required("sigClass", "body", m.SigClass); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wei bu signature base based on context it is used
func (m *WeiBuSignatureBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WeiBuSignatureBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeiBuSignatureBase) UnmarshalBinary(b []byte) error {
	var res WeiBuSignatureBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
