name: Scan Code with FindCode

on:
  push:
    branches: [main]
  workflow_dispatch:  # 添加手动触发事件
    inputs:
      target-path:
        description: '扫描目标路径'
        default: './'
        required: false
      code-type:
        description: '代码类型'
        default: 'go-swagger'
        required: false

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run FindCode Action
        uses: TSY244/FindCode-Action@main
        with:
          target-path: ./
          code-type: go-swagger
          output-report: ./report/findcode-results.txt

      - name: Upload FindCode report
        uses: actions/upload-artifact@v4.6.2  # 升级到 v4
        with:
          name: findcode-report
          path: ./report/
          retention-days: 7