name: Scan Code with FindCode

on:
  push:
    branches: [main]
  workflow_dispatch:  # 添加手动触发事件
    inputs:
      target-path:
        description: '扫描目标路径'
        default: './'
        required: false
      code-type:
        description: '代码类型'
        default: 'go-swagger'
        required: false

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 创建报告目录（宿主机和容器共享此路径）
      - name: Prepare report directory
        run: mkdir -p $GITHUB_WORKSPACE/report

      - name: Run FindCode Action
        uses: TSY244/FindCode-Action@v2.1.1
        with:
          target-path: ./
          code-type: go-swagger
#          output-report: ${{ github.workspace }}/report/findcode-results.txt  # 绝对路径
          output-report: $GITHUB_WORKSPACE/report/findcode-results.txt  # 关键点：使用共享路径

      - name: Upload FindCode report
        uses: actions/upload-artifact@v4
        with:
          name: findcode-report
#          path: ${{ github.workspace }}/report/  # 绝对路径
          path: $GITHUB_WORKSPACE/report/