name: Scan Code with FindCode

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run FindCode Action
        uses: TSY244/FindCode-Action@v2
        with:
          target-path: ./
          code-type: go-swagger
          output-report: ./report/findcode-results.txt

      - name: Upload FindCode report
        uses: actions/upload-artifact@v4.6.2  # 升级到 v4
        with:
          name: findcode-report
          path: ./report/
          retention-days: 7